entity-section-limiter:
  limit-per-section: 128
  ignore-named: true
  ignore-tamed: true
  remove-strategy: 0
  ignored-entity:
    - ELDER_GUARDIAN
    - VILLAGER
    - IRON_GOLEM
    - SNOWMAN
    - PAINTING
    - ITEM_FRAME
    - GLOW_ITEM_FRAME
    - PRIMED_TNT
    - FALLING_BLOCK
    - ARMOR_STAND
    - MINECART_CHEST
    - MINECART_HOPPER
  custom-limits:
    minecarts:
      entity:
        - MINECART
        - MINECART_CHEST
        - MINECART_HOPPER
      exclusive: false
      limit-section: 5
      limit-chunk: 15
global-redstone-limiter:
  enabled: true
  tick-length: 5
  limit: 1024
prevent-entity-portal:
  - SNOWBALL
tile-entity-limiter:
  enabled: true
  limit: 128
  period: 1200